### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by chris-mc1** [tsangwpx/aioqbt#2]
Using the example from the readme, I get an ForbiddenError when connecting to an qBittorrent instance which requires a password, but works fine when Authentication is disabled

```
Request 1/3: GET 'http://192.168.1.74:8080/api/v2/app/version'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 255, in request
    raise aiohttp.ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.1.74:8080/api/v2/app/version')
Request 1/3: GET 'http://192.168.1.74:8080/api/v2/app/webapiVersion'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 255, in request
    raise aiohttp.ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.1.74:8080/api/v2/app/webapiVersion')
Request 1/3: GET 'http://192.168.1.74:8080/api/v2/app/version'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 255, in request
    raise aiohttp.ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.1.74:8080/api/v2/app/version')
Request 1/1: POST 'http://192.168.1.74:8080/api/v2/auth/logout'
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 255, in request
    raise aiohttp.ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.1.74:8080/api/v2/app/version')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspaces/qbit/test2.py", line 16, in main
    print(await client.app.version())  # v4.6.1
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioqbt/api/app.py", line 18, in version
    return await self._request_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 518, in _request_text
    return await self._client().request_text(method, endpoint, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 363, in request_text
    resp = await self.request(method, endpoint, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 284, in request
    self._handle_error(last_exc, resp, resp_body)
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 351, in _handle_error
    raise exc_class.from_response(resp, message) from error
aioqbt.exc.ForbiddenError: ForbiddenError(status=403, message='Forbidden')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 255, in request
    raise aiohttp.ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.1.74:8080/api/v2/auth/logout')
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 255, in request
    raise aiohttp.ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 403, message='Forbidden', url=URL('http://192.168.1.74:8080/api/v2/app/version')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/root/.vscode-server-insiders/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/__main__.py", line 39, in <module>
    cli.main()
  File "/root/.vscode-server-insiders/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 430, in main
    run()
  File "/root/.vscode-server-insiders/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/adapter/../../debugpy/launcher/../../debugpy/../debugpy/server/cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "/root/.vscode-server-insiders/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 321, in run_path
    return _run_module_code(code, init_globals, run_name,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.vscode-server-insiders/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 135, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "/root/.vscode-server-insiders/extensions/ms-python.debugpy-2024.0.0-linux-x64/bundled/libs/debugpy/_vendored/pydevd/_pydevd_bundle/pydevd_runpy.py", line 124, in _run_code
    exec(code, run_globals)
  File "/workspaces/qbit/test2.py", line 26, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 190, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/workspaces/qbit/test2.py", line 16, in main
    print(await client.app.version())  # v4.6.1
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioqbt/api/app.py", line 18, in version
    return await self._request_text(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 518, in _request_text
    return await self._client().request_text(method, endpoint, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 363, in request_text
    resp = await self.request(method, endpoint, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 284, in request
    self._handle_error(last_exc, resp, resp_body)
  File "/usr/local/lib/python3.11/site-packages/aioqbt/client.py", line 351, in _handle_error
    raise exc_class.from_response(resp, message) from error
aioqbt.exc.ForbiddenError: ForbiddenError(status=403, message='Forbidden')
```

**Comment by tsangwpx** [comment]
The issue is due to IP address in URL host. Ref: [aiohttp#1183](https://github.com/aio-libs/aiohttp/issues/1183).

Two solutions:
1. Use a domain name instead, or;
2. Pass an instance of ClientSession with `CookieJar(unsafe=True)`, and close it properly after use.

For example,

```python
import asyncio

from aioqbt.api import InfoFilter
from aioqbt.client import create_client
from aiohttp import ClientSession, CookieJar


async def main():
    async with ClientSession(cookie_jar=CookieJar(unsafe=True)) as http:
        client = await create_client(
            "http://127.0.0.1:8888/api/v2/",
            username="admin",
            password="adminadmin",
            http=http,
        )

        async with client:
            # print client and API versions
            print(await client.app.version())  # v4.6.1
            print(await client.app.webapi_version())  # 2.9.3

            # print torrents in downloading
            for info in await client.torrents.info(filter=InfoFilter.DOWNLOADING):
                print(f"{info.added_on.isoformat()} added {info.name!r}")
                # 2023-11-06T17:59:00 added 'ubuntu-22.04.3-desktop-amd64.iso'


if __name__ == "__main__":
    asyncio.run(main())

```

I will mention this behavior somewhere in the doc.

**Comment by chris-mc1** [comment]
Thanks, got it working now
